### PR TITLE
initial typescript implementation

### PR DESCRIPTION
**Pull request by ecwyne**
This looks like a very interesting idea. I saw an interest in using typescript, so I used this as an opportunity to learn about how this package works by converting it to typescript. Let me know what you think!

### CODE REVIEW

**Comment by ptpaterson** [comment]
Hi @ecwyne.  First, that was insanely fast!  Thanks!

I've got the examples working and picking away at committing them to the merge request.

**Comment by ptpaterson** [comment]
I really do think the typings help sort things out, especially with the curried functions about.

**Comment by ptpaterson** [comment]
Would you say that tsdx is appropriate for this project or just a familiar and convenient way to get started?  That's an honest question, I have done little configuration for Typescript on my own, and I'm also new to publishing anything.

**Comment by ecwyne** [comment]
@ptpaterson I'm glad to hear it was helpful! I've only ever published one package with `tsdx` but it was very useful. From what I understand it makes it way easier to publish it to the most popular architectures and has a pretty slick DX

**Pull request merged**
